# Generated by Django 5.1.4 on 2024-12-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fecha_orden',
        ),
        migrations.AddField(
            model_name='factura',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
