# Generated by Django 5.1.4 on 2024-12-13 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_factura_fecha_orden_factura_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='linea_de_factura',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
